### ISSUE TITLE
Fact check of marketing claims

### ISSUE THREAD

**Issue by miohtama** [unstoppabledomains/unstoppable-chat#1]
Hi,

As UnstoppableDomains have come out with their chat product and some fanfare, I hope to fact check some of the claims touted by the press.

First of all, the P2P storage network is referred on UnstoppableDomains home page:

<img width="661" alt="image" src="https://user-images.githubusercontent.com/49922/87163562-d53c4a00-c2c7-11ea-876a-e24ca93a4f94.png">

I hope you could name the Gun here, as it would be nice to give the credit where the credit is due, as Gun project predates UnstoppableDomains quite a few years and you are relying solely on Gun based protocols, as far as I can see.

Another claim is that the data is stored in the network. Unlike in Storj, FileCoin or Sia, there is no guarantees of how long the data lives in the network. While it is suitable for online chat, it would be honest to have more upfront data on how long chat channels (rooms) can survive and other limitations of the network. What are the limitations of the RAD storage, especially as there are no economic incentives for the node operators?

Furthermore there are limitations how you use Gun itself. Currently, you connect to one supernode - on Heroku. As this cannot be a long term solution, it would be nice to know what are the characteristics of the network attack resistance.

As the cryptocurrency industry is full of hype and untruthful claims, for the credibility of your excellent project, I propose you are more accurate fact-based and technical your public communications.

**Comment by jamesrez** [comment]
@miohtama Hi miohtama, thanks for taking the time to write that. I'll do my best to address what I can.

I agree that Gun could be mentioned more, but do note that we include the Gun logo on the [/chat](https://unstoppabledomains.com/chat) page

You're right about the heroku supernode, to which we can connect to as many as we like, but right now we only connect to one. I suppose we should be adding more.

Also if there's one thing I know about Gun, is that it is really tough to get rid of data. If I were to delete all of the data on the one supernode's s3 storage, it would likely have zero effect and the system would resync all the data back. This is because the chat data is saved in each users' browser. Gun does its best to save and sync all the data throughout all available peers, meaning all users are also saving each others' data. 

We also plan to include other protocols into dChat. I even know that a [threads](https://github.com/textileio/js-threads) chat system is being worked on right now.

Hope that clears up some things, and perhaps we should be expressing these things more. dChat is still in an early state, and we plan to keep releasing the protocol to be better and better. Thanks for your rational critique.

**Comment by miohtama** [comment]
Thank you for the clarification @JamieRez !
